name: AppleHealth CI

on:
    workflow_dispatch:
        inputs:
            mode:
                description: 'Mode'
                required: true
                default: 'add'
            date:
                description: 'Date'
                required: true
            value:
                description: 'Value'
                required: true
            type:
                description: 'Type'
                required: true
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run dev script with parameters
              run: npm run dev -- --mode ${{ github.event.inputs.mode }} --date ${{ github.event.inputs.date }} --value ${{ github.event.inputs.value }} --type ${{ github.event.inputs.type }}

            - name: Commit changes
              run: |
                  git config --local user.name "mk965"
                  git config --local user.email "mencre@163.com"
                  git add .
                  git commit -m "Update data"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.ISTATUS_TOKEN }}

            # - name: Commit Change
            #   run: |
            #       git config --local user.name "mk965"
            #       git config --local user.email "mencre@163.com"
            #       git pull
            #       git add .
            #       git commit -m 'update data' || echo "nothing to commit"
            #       git push || echo "nothing to push"
